#!/usr/bin/env bash
# Create a git worktree for working on one demo, sharing the heavy Lean build
# artifacts with the main checkout so a new worktree does NOT re-fetch or rebuild
# Mathlib (~6.6G) or the local toolchain (~22G in deps/).
#
# What is shared (symlinked; read-only in practice, so safe across concurrent
# worktrees — the dependency sources never change, so Lake never rebuilds them):
#   - deps/                          the local toolchain + path-dep sources/builds
#   - demos/lean/.lake/packages/     the resolved package cache (Mathlib, aesop, …)
#
# What is per-worktree (isolated, cheap to rebuild — kept separate so parallel
# agents never clobber each other's compile of the Demos library):
#   - the branch's source, demos/lean/Demos/Extracted/ (regenerated by `make extract`),
#     and demos/lean/.lake/build/ (the ~39M Demos-library output).
#
# Usage:   scripts/dev-worktree.sh <name>            e.g.  scripts/dev-worktree.sh demo4
# Teardown (after the branch is merged):
#          git worktree remove .worktrees/<name>     # drops the worktree + its symlinks
#          git branch -d <name>
#
# Prereq: the MAIN checkout must already be built (deps/ + demos/lean/.lake/packages
# populated) — run `make` in the main checkout once first.
set -euo pipefail

name="${1:?usage: dev-worktree.sh <name>}"
main="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
wt="$main/.worktrees/$name"

if [ -e "$wt" ]; then echo "error: worktree path already exists: $wt" >&2; exit 1; fi
if [ ! -d "$main/demos/lean/.lake/packages" ]; then
  echo "error: $main/demos/lean/.lake/packages missing — build the main checkout first (make)" >&2
  exit 1
fi

# New branch <name> off current HEAD, or attach the branch if it already exists.
if git -C "$main" show-ref --verify --quiet "refs/heads/$name"; then
  git -C "$main" worktree add "$wt" "$name"
else
  git -C "$main" worktree add "$wt" -b "$name"
fi

# Share the toolchain/path-deps and the resolved package cache. Absolute symlinks
# (the depth is awkward for relative ones, and absolute keeps any cached absolute
# olean paths consistent with the main checkout).
ln -s "$main/deps" "$wt/deps"
mkdir -p "$wt/demos/lean/.lake"
ln -s "$main/demos/lean/.lake/packages" "$wt/demos/lean/.lake/packages"

cat <<EOF

worktree ready: $wt   (branch: $name)
  shared:    deps/ + demos/lean/.lake/packages/   → no Mathlib re-fetch/rebuild
  isolated:  branch source, Demos/Extracted/, .lake/build/
next:        cd "$wt" && make          # builds only the Demos library
verify:      cd "$wt" && make verify
EOF
